eclipse-xpanse/xpanse-ui

- .github/workflows/xpanse.yml
> Add code format.

- src/components/content/order/CreateService.tsx
- src/components/content/order/Services.tsx
- src/components/utils/Sort.ts
- src/styles/service_order.css
fix  eclipse-xpanse/xpanse#221
> Add latest version tag for service on service order page.

- src/components/content/register/DisplayOclData.tsx
- src/styles/register.css
added scroll bar when the scripts are too big
> fix display for large deployment scripts

- src/components/content/order/CreateService.tsx
Fix to refresh default selected region list when the version changes. (in case the newly selected version has a different list of regions).
> update selected region when version is changed.

- src/components/content/order/ServiceList.tsx
> Update  deployed services list page button text.

- src/components/content/catalog/Catalog.tsx
- src/components/content/catalog/services/ServiceDetail.tsx
- src/components/content/catalog/services/ServiceProvider.tsx
- src/components/content/catalog/services/UnregisterService.tsx
- src/components/content/catalog/services/UpdateResult.tsx
- src/components/content/catalog/services/UpdateService.tsx
- src/components/content/catalog/services/updateServiceResult.ts
- src/components/content/register/OclSummaryDisplay.tsx
- src/components/content/register/RegisterPanel.tsx
- src/components/content/register/YamlSyntaxValidationResult.tsx
- src/styles/catalog.css
> add update and unregister button for catalog page.

- src/components/content/catalog/Catalog.tsx
- src/components/content/catalog/services/ServiceProvider.tsx
- src/components/content/catalog/services/UnregisterService.tsx
> Set the first subtree of the Catalog to be selected by default.

- src/components/content/order/OrderSubmit.tsx
Fixes eclipse-xpanse/xpanse#222
> display order ID in final page

- src/components/content/home/WelcomeCard.tsx
website URLs have been somehow reverted to old ones. Have changed it again.
> revert wrong commits

- src/components/content/order/CreateService.tsx
- src/components/content/order/Services.tsx
fix eclipse-xpanse/xpanse#219
When the service name has spaces in it, The GUI will get rid of the spaces, so It will find nothing to been show on the GUI.
> Fix the service name that has spaces in it

- src/components/content/order/Services.tsx
> fix warning at services page.

- src/styles/service_order.css
> Fix the width of the back on the order page.

- src/components/content/order/CreateService.tsx
- src/components/content/order/Navigate.tsx
- src/components/content/order/OrderSubmit.tsx
- src/components/content/order/formElements/GoToSubmit.tsx
>  fix issues of  227(Keep the previous selections for the Back navigation).

- src/components/layouts/sider/LayoutSider.tsx
- src/components/layouts/sider/MenuLoading.tsx
- src/styles/app.css
Fixes  eclipse-xpanse/xpanse#269
> show spinner while side menu is loaded

- src/components/content/order/ApiDoc.tsx
- src/components/content/order/OrderSubmit.tsx
- src/components/content/order/formElements/GoToSubmit.tsx
- src/styles/app.css
- src/styles/service_order.css
fixed eclipse-xpanse/xpanse#262
> Integrate the service API documents to the GUI

- src/components/content/order/ApiDoc.tsx
- src/components/content/register/RegisterPanel.tsx
- src/components/content/register/RegisterResult.tsx
- src/components/content/register/registerService.ts
- src/xpanse-api/generated/types/ObjectParamAPI.ts
- src/xpanse-api/generated/types/ObservableAPI.ts
- src/xpanse-api/generated/types/PromiseAPI.ts
Fixes eclipse-xpanse/xpanse#275
> #show registration details

- src/components/content/catalog/services/ServiceProvider.tsx
- src/xpanse-api/generated/models/ObjectSerializer.ts
> Turn to call the /services/avaliable/xxx API in the pages of the end-user.

- src/components/content/catalog/Catalog.tsx
- src/components/content/order/CreateService.tsx
- src/components/content/order/Services.tsx
- src/components/content/register/registerService.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/apis/ServiceVendorApi.ts
- src/xpanse-api/generated/apis/ServicesAvailableApi.ts
- src/xpanse-api/generated/models/Response.ts
- src/xpanse-api/generated/types/ObjectParamAPI.ts
- src/xpanse-api/generated/types/ObservableAPI.ts
- src/xpanse-api/generated/types/PromiseAPI.ts
must be merged with the /eclipse-xpanse/xpanse#298 at the same time.
> use ServiceVoCategoryEnum

- src/components/content/catalog/services/ServiceDetail.tsx
- src/components/content/order/ApiDoc.tsx
- src/components/content/order/OrderSubmit.tsx
- src/styles/app.css
- src/styles/service_order.css
Fixes  eclipse-xpanse/xpanse#294
> show API doc in service catalog

- src/components/content/order/CreateService.tsx
- src/components/content/order/formElements/GoToSubmit.tsx
related to eclipse-xpanse/xpanse#289.
> update api for CreateService.

- src/components/content/order/MyServiceDetails.tsx
- src/components/content/order/ServiceList.tsx
- src/components/utils/generateUnorderedList.tsx
- src/styles/service_instance_list.css
Fixed eclipse-xpanse/xpanse#257
> Show properties of the deployed services on MyServices list.

- src/components/content/order/OrderSubmit.tsx
- src/components/content/order/ServiceList.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/apis/AdminApi.ts
- src/xpanse-api/generated/apis/ServiceApi.ts
- src/xpanse-api/generated/apis/ServiceVendorApi.ts
- src/xpanse-api/generated/apis/ServicesAvailableApi.ts
- src/xpanse-api/generated/models/Response.ts
- src/xpanse-api/generated/types/ObjectParamAPI.ts
- src/xpanse-api/generated/types/ObservableAPI.ts
- src/xpanse-api/generated/types/PromiseAPI.ts
> update api for ServiceList and OrderSubmit.

- src/components/content/order/formElements/CommonTypes.ts
- src/components/content/order/formElements/GoToSubmit.tsx
- src/components/content/order/formElements/TextInput.tsx
- src/xpanse-api/generated/models/DeployVariable.ts
fixed eclipse-xpanse/xpanse#304
> Add a sensitive flag for hidden the input on the GUI

- src/components/content/order/OrderSubmit.tsx
- src/components/content/order/ServiceList.tsx
- src/components/content/order/formElements/GoToSubmit.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/CreateRequest.ts
- src/xpanse-api/generated/models/DeployVariable.ts
- src/xpanse-api/generated/models/ServiceDetailVo.ts
- src/xpanse-api/generated/models/ServiceVo.ts
- src/xpanse-api/generated/services/ServiceService.ts
- src/xpanse-api/generated/services/ServicesAvailableService.ts
fixes eclipse-xpanse/xpanse#287
> send username details

- src/components/content/order/Services.tsx
- src/components/content/order/ServicesLoadingError.tsx
- src/styles/service_order.css
We will show this error now if the API call fails.
> show error when API returns error

- package-lock.json
- package.json
- src/components/content/order/CreateService.tsx
- src/components/content/order/OrderSubmit.tsx
- src/components/content/order/ServiceList.tsx
- src/components/content/order/formElements/CspSelect.tsx
- src/components/content/order/formElements/GoToSubmit.tsx
- src/components/content/order/formElements/TextInput.tsx
- src/components/content/systemStatus/SystemStatusBar.tsx
1. Bump dependency versions. 
2. fix issues reported by new linter version.
> bump dependency versions

- src/xpanse-api/api.json
- src/xpanse-api/generated/index.ts
- src/xpanse-api/generated/models/Metric.ts
- src/xpanse-api/generated/models/MetricItem.ts
- src/xpanse-api/generated/services/MonitorService.ts
generate monitor api.
related eclipse-xpanse/xpanse#292
> generate monitor api.

- package.json
- src/App.tsx
- src/components/content/monitor/Monitor.tsx
- src/components/content/monitor/MonitorChart.tsx
- src/components/content/monitor/MonitorTip.tsx
- src/components/content/monitor/metricProps.ts
- src/components/content/order/ServicesMenu.tsx
- src/components/layouts/sider/LayoutSider.tsx
- src/components/utils/Queue.ts
- src/components/utils/constants.tsx
- src/styles/monitor.css
add monitor gui.
fixed eclipse-xpanse/xpanse/issues/292
> add monitor gui.

- src/components/content/order/ServiceList.tsx
fixd eclipse-xpanse/xpanse#362
> update api for MyServices.

- src/components/content/monitor/Monitor.tsx
- src/components/content/monitor/MonitorChart.tsx
- src/components/content/monitor/MonitorTip.tsx
- src/components/content/monitor/metricProps.ts
- src/components/utils/constants.tsx
- src/styles/monitor.css
related eclipse-xpanse/xpanse#373
fixed eclipse-xpanse/xpanse#367
> update monitor gui.

- src/components/content/monitor/Monitor.tsx
- src/components/content/monitor/MonitorChart.tsx
- src/components/content/monitor/metricProps.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/index.ts
- src/xpanse-api/generated/models/AbstractCredentialInfo.ts
- src/xpanse-api/generated/models/CreateCredential.ts
- src/xpanse-api/generated/models/CredentialDefinition.ts
- src/xpanse-api/generated/models/CredentialVariable.ts
- src/xpanse-api/generated/models/Metric.ts
- src/xpanse-api/generated/models/MetricItem.ts
- src/xpanse-api/generated/services/CredentialsManagementService.ts
- src/xpanse-api/generated/services/ServicesAvailableService.ts
> display metric unit

- src/components/content/catalog/services/ServiceProvider.tsx
- src/components/content/order/formElements/CspSelect.tsx
- src/xpanse-api/generated/models/CloudServiceProvider.ts
> Catalog show logo of Csp

- src/components/content/order/DeploymentFailed.tsx
- src/components/content/order/OrderSubmit.tsx
- src/components/content/order/ServiceList.tsx
- src/xpanse-api/generated/models/ServiceDetailVo.ts
> show result message when deploy or destroy failed.

- src/components/content/order/ServiceList.tsx
> add confirmation before destroying.

- src/xpanse-api/api.json
- src/xpanse-api/generated/models/AbstractCredentialInfo.ts
- src/xpanse-api/generated/models/CredentialVariable.ts
fix  eclipse-xpanse/xpanse#423
> Fix AbstractCredentialInfo for credentials API.

- src/components/content/monitor/Monitor.tsx
fixes eclipse-xpanse/xpanse#433
> update monitor metric api.

- src/App.tsx
- src/components/content/credential/AddCredential.tsx
- src/components/content/credential/Credential.tsx
- src/components/content/credential/CredentialDetails.tsx
- src/components/content/credential/CredentialTip.tsx
- src/components/content/credential/UpdateCredential.tsx
- src/components/content/order/ServicesMenu.tsx
- src/components/layouts/sider/LayoutSider.tsx
- src/components/utils/constants.tsx
- src/styles/credential.css
Fixed eclipse-xpanse/xpanse#424  
fixes eclipse-xpanse/xpanse#425 
fixes eclipse-xpanse/xpanse#426
fixes eclipse-xpanse/xpanse#419
> Credentials Management UI

- src/components/content/catalog/services/ServiceDetail.tsx
- src/components/content/register/DisplayOclData.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/Response.ts
- src/xpanse-api/generated/models/UserAvailableServiceVo.ts
fixed eclipse-xpanse/xpanse#528
> display credential type in register, update and catalog UI

- src/components/content/order/ServiceList.tsx
fix eclipse-xpanse/xpanse#577
Note - additionally contains a small fix to remove old errors while refreshing service list.
> fix error in my services loading

- package.json
- src/components/content/credential/AddCredential.tsx
- src/components/content/credential/Credential.tsx
- src/components/content/credential/UpdateCredential.tsx
- src/components/content/monitor/Monitor.tsx
- src/components/content/order/OrderSubmit.tsx
- src/components/content/order/formElements/CommonTypes.ts
- src/components/content/order/migrate/MigrateService.tsx
- src/components/layouts/header/HeaderUserRoles.tsx
- src/components/protectedRoutes/ProtectedRoute.tsx
remove unnecessary ES disable comments
> remove eslint disable

- src/App.tsx
- src/components/notFound/NotFoundPage.tsx
fixes eclipse-xpanse/xpanse#615
> Add not found page.

- src/components/content/catalog/services/UpdateResult.tsx
- src/components/content/register/RegisterResult.tsx
- src/styles/catalog.css
> fix warnings

- src/App.tsx
- src/components/content/order/ServicesMenu.tsx
- src/components/content/systemStatus/HealthCheckStatus.tsx
- src/components/content/systemStatus/SystemStatusBar.tsx
- src/components/content/systemStatus/useHealthCheckStatusQuery.ts
- src/components/layouts/sider/LayoutSider.tsx
- src/components/oidc/OidcConfig.tsx
- src/components/protectedRoutes/ProtectedRoute.tsx
- src/components/utils/constants.tsx
- src/styles/health_status.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/index.ts
- src/xpanse-api/generated/models/BackendSystemStatus.ts
- src/xpanse-api/generated/models/Response.ts
- src/xpanse-api/generated/models/SystemStatus.ts
- src/xpanse-api/generated/models/TokenResponse.ts
- src/xpanse-api/generated/services/AdminService.ts
- src/xpanse-api/generated/services/AuthManagementService.ts
- src/xpanse-api/generated/services/CredentialsManagementService.ts
- src/xpanse-api/generated/services/MonitorService.ts
- src/xpanse-api/generated/services/ServiceService.ts
- src/xpanse-api/generated/services/ServiceVendorService.ts
- src/xpanse-api/generated/services/ServicesAvailableService.ts
fixes eclipse-xpanse/xpanse#618
> display HealthCheck status.

- src/components/layouts/sider/LayoutSider.tsx
- src/components/layouts/sider/menuItems.ts
fixed eclipse-xpanse/xpanse#643
> remove unnecessary useEffect hook

- src/components/content/order/CreateService.tsx
> remove wrong defaults

- src/App.tsx
- src/components/content/catalog/CatalogMainMenu.tsx
- src/components/content/catalog/CategoryCatalog.tsx
fixes eclipse-xpanse/xpanse#635
> load services only when category is selected

- src/components/content/credential/AddCredential.tsx
Fixed eclipse-xpanse/xpanse#661
> handle adding multiple credentials

- src/components/oidc/OidcConfig.tsx
fixes eclipse-xpanse/xpanse#657
> set default role when no roles are assigned

- src/components/content/catalog/CategoryCatalog.tsx
fixes eclipse-xpanse/xpanse#680
> reload data when page is opened again

- src/components/content/myServices/MyServices.tsx
fixes eclipse-xpanse/xpanse#677
> remove alert on success

- src/components/content/catalog/CategoryCatalog.tsx
- src/components/content/catalog/services/ServiceDetail.tsx
- src/components/content/catalog/services/ShowIcon.tsx
- src/styles/catalog.css
fixes eclipse-xpanse/xpanse#681
> show service icon in catalog.

- src/components/content/order/create/OrderSubmitStatusPolling.tsx
- src/components/content/order/orderStatus/useServiceDetailsPollingQuery.ts
fixes eclipse-xpanse/xpanse#688
> start polling only after request ID is generated

- src/components/content/credential/AddCredential.tsx
- src/components/content/credential/Credential.tsx
fixed https://github.com/eclipse-xpanse/xpanse/issues/693
Before:
After:
> Remove column 'user' from credentials

- src/components/content/credential/AddCredential.tsx
Fixed eclipse-xpanse/xpanse#694
> UI - Add Credential filed 'Description' should not be blank in the form.

- src/components/content/credential/AddCredential.tsx
- src/components/content/credential/Credential.tsx
Fixed eclipse-xpanse/xpanse#701
> fixed add credential for react-query

- src/components/content/myServices/MyServices.tsx
- src/components/content/order/formElements/CommonTypes.ts
- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/migrate/MigrateService.tsx
- src/components/content/order/migrate/MigrateServiceStatusPolling.tsx
- src/components/content/order/orderStatus/ProcessingStatus.tsx
Fixed eclipse-xpanse/xpanse#673 
Fixed eclipse-xpanse/xpanse#695
> switch to react-query for migrate of myServices table

- .github/workflows/ui-docker-image.yml
- README.md
- docker/Dockerfile
- docker/nginx-entrypoint.sh
- docker/nginx.conf
- package.json
- public/index.html
- public/inject.js
- src/App.tsx
- src/components/oidc/OidcConfig.tsx
- src/config/config.ts
- src/config/index.d.ts
- src/xpanse-api/CustomOpenApiConfig.ts
related to https://github.com/eclipse-xpanse/xpanse/issues/702
> inject environment variables

- src/components/content/monitor/MetricChartsPerRow.tsx
- src/components/content/monitor/MetricIsAutoRefresh.tsx
- src/components/content/monitor/MetricOptionDataByChartsPerRow.tsx
- src/components/content/monitor/MetricTimePeriod.tsx
- src/components/content/monitor/Monitor.tsx
- src/components/content/monitor/MonitorChart.tsx
- src/components/content/monitor/metricProps.ts
- src/components/content/monitor/useDeployedServicesByUserQuery.ts
- src/components/content/systemStatus/useHealthCheckStatusQuery.ts
- src/components/oidc/OidcConfig.tsx
fixes eclipse-xpanse/xpanse#627
> switch useQuery for monitor.

- src/components/content/catalog/CategoryCatalog.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/709
> disable unnecessary refetch

- src/components/content/order/create/CreateService.tsx
- src/components/content/order/formElements/CommonTypes.ts
- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/migrate/MigrateService.tsx
- src/components/content/order/migrate/SelectDestination.tsx
- src/components/content/order/migrate/ShowDeploy.tsx
fixes eclipse-xpanse/xpanse#691
Migrate:
> use version and csp filter flavor.

- src/components/content/monitor/MonitorChart.tsx
- src/components/content/order/create/CreateService.tsx
- src/components/content/order/migrate/Migrate.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/OpenAPI.ts
- src/xpanse-api/generated/services/MonitorService.ts
- src/xpanse-api/generated/services/ServiceCatalogService.ts
- src/xpanse-api/generated/services/ServiceVendorService.ts
fixed https://github.com/eclipse-xpanse/xpanse/issues/718
related https://github.com/eclipse-xpanse/xpanse/pull/724
> Refactor Monitor API

- src/components/content/credential/Credential.tsx
Fixed eclipse-xpanse/xpanse#728
> UI - credentials page error not clear on successful reload

- src/components/content/monitor/MonitorChart.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/730
> remove cache for metrics query

- src/App.tsx
- src/components/layouts/sider/menuItems.ts
- src/components/oidc/OidcConfig.tsx
- src/components/protectedRoutes/ProtectedRoute.tsx
> Rename the role 'CSP' to 'ISV'

- src/components/content/credential/AddCredential.tsx
- src/components/content/credential/UpdateCredential.tsx
Fixed eclipse-xpanse/xpanse#729
> UI - Credentials - implement loading status

- src/components/content/catalog/CategoryCatalog.tsx
- src/components/content/catalog/services/ServiceProvider.tsx
- src/components/content/catalog/services/catalogProps.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/services/CredentialsManagementService.ts
fixes eclipse-xpanse/xpanse#732
> update catalog Api.

- src/components/content/monitor/useDeployedServicesByUserQuery.ts
- src/components/content/myServices/MyServiceDetails.tsx
- src/components/content/myServices/MyServices.tsx
- src/components/content/order/create/OrderSubmitStatusPolling.tsx
- src/components/content/order/destroy/DestroyServiceStatusPolling.tsx
- src/components/content/order/migrate/MigrateServiceStatusPolling.tsx
- src/components/content/order/orderStatus/useServiceDetailsPollingQuery.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/services/AdminService.ts
- src/xpanse-api/generated/services/ServiceCatalogService.ts
- src/xpanse-api/generated/services/ServiceService.ts
- src/xpanse-api/generated/services/ServiceVendorService.ts
fixed https://github.com/eclipse-xpanse/xpanse/issues/722
related https://github.com/eclipse-xpanse/xpanse/pull/739
> Refactor Deploy API

- src/components/content/credential/Credential.tsx
Fixed eclipse-xpanse/xpanse#741
> provide refresh/reload button on credentials page

- src/components/content/order/services/Services.tsx
related eclipse-xpanse/xpanse#732
> update Services Api.

- src/components/content/order/create/CreateService.tsx
- src/components/content/order/services/Services.tsx
- src/components/content/order/services/ServicesLoadingError.tsx
fixes eclipse-xpanse/xpanse#752
> add loading when useQuery isLoading for Services.

- src/components/content/register/DisplayOclData.tsx
fixes eclipse-xpanse/xpanse#765
> show csp logo.

- .env
fixed https://github.com/eclipse-xpanse/xpanse/issues/614
related https://github.com/eclipse-xpanse/xpanse-iam/pull/6
> set default local service url of zitadel

- src/components/content/credential/AddCredential.tsx
- src/components/content/home/WelcomeCard.tsx
- src/components/content/home/__tests__/Home.test.tsx
> fix website links

- src/components/content/catalog/services/ServiceDetail.tsx
- src/components/content/catalog/services/UpdateService.tsx
- src/components/content/common/BillingText.tsx
- src/components/content/common/DeploymentText.tsx
- src/components/content/common/DisplayOclData.tsx
- src/components/content/common/FlavorsText.tsx
- src/components/content/common/OclSummaryDisplay.tsx
- src/components/content/home/WelcomeCard.tsx
- src/components/content/register/RegisterPanel.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/764
> unify register, catalog and update screens

- src/components/content/catalog/CategoryCatalog.tsx
- src/components/content/catalog/services/ServiceDetail.tsx
- src/components/content/catalog/services/ServiceStatus.tsx
- src/components/content/catalog/services/UpdateService.tsx
- src/components/content/monitor/Monitor.tsx
- src/components/content/myServices/MyServiceStatus.tsx
- src/components/content/myServices/MyServices.tsx
- src/components/content/order/create/OrderSubmitStatusPolling.tsx
- src/components/content/order/destroy/DestroyServiceStatusPolling.tsx
- src/components/content/order/migrate/MigrateServiceStatusPolling.tsx
- src/components/content/order/orderStatus/DeploymentTimer.tsx
- src/components/content/order/orderStatus/ProcessingStatus.tsx
- src/components/utils/generateUnorderedList.tsx
- src/styles/catalog.css
- src/styles/my_services.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/DeployVariable.ts
- src/xpanse-api/generated/models/ServiceDetailVo.ts
- src/xpanse-api/generated/models/ServiceTemplateVo.ts
- src/xpanse-api/generated/models/ServiceVo.ts
- src/xpanse-api/generated/services/ServiceService.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/799
> use different tags for order statuses

- src/components/content/order/create/Navigate.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/services/Services.tsx
- src/components/content/order/store/OrderFormStore.ts
- src/styles/catalog.css
related to https://github.com/eclipse-xpanse/xpanse/issues/806
fix findings with current deploy variables store. 
current issues
1. Only last entered form field is stored. 
2. sometimes the last character is not stored. 
3. Default values are stored. We must store only user entered values.
> refactor form value store

- src/components/content/myServices/MyServices.tsx
correct wrong status enum which was updated in the previous PR.
> fix wrong status check

- src/components/content/order/migrate/Migrate.tsx
https://github.com/eclipse-xpanse/xpanse-ui/assets/42802200/f1d97c78-62b7-426b-a1f4-1273c3d1e167
> make migrate can select CSP.

- package-lock.json
- package.json
- src/components/content/catalog/services/unregister/UnregisterService.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
- src/components/content/credential/Credential.tsx
- src/components/content/monitor/Monitor.tsx
- src/components/content/myServices/MyServices.tsx
- src/components/content/order/create/Navigate.tsx
- src/components/content/order/formElements/CommonTypes.ts
- src/components/content/order/formElements/GoToSubmit.tsx
- src/components/content/order/migrate/ExportServiceData.tsx
- src/components/content/order/migrate/ImportServiceData.tsx
- src/components/content/order/migrate/MigrateService.tsx
- src/components/content/order/migrate/SelectDestination.tsx
- src/components/content/order/migrate/ShowDeploy.tsx
- src/components/content/order/services/Services.tsx
- src/components/layouts/header/HeaderUserRoles.tsx
- src/components/layouts/sider/LayoutSider.tsx
- src/components/protectedRoutes/NotAuthorized.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/820
> update versions and enable new eslint rules

- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/ServiceDetailVo.ts
- src/xpanse-api/generated/models/ServiceTemplateVo.ts
- src/xpanse-api/generated/models/ServiceVo.ts
- src/xpanse-api/generated/models/UserAvailableServiceVo.ts
- src/xpanse-api/generated/services/ServiceService.ts
- src/xpanse-api/generated/services/ServiceVendorService.ts
fixed https://github.com/eclipse-xpanse/xpanse/issues/823
related https://github.com/eclipse-xpanse/xpanse/pull/828
> Using service_templete APIs on the catalog menu list for the role isv

- src/components/content/common/doc/CredentialApiDoc.tsx
- src/components/content/credential/AddCredential.tsx
- src/components/content/credential/CredentialApiDoc.tsx
- src/components/content/credential/UpdateCredential.tsx
- src/styles/credential.css
Fixed eclipse-xpanse/xpanse#782
> show credentials openapi documentation in add/update credentials UI

- src/components/content/credential/AddCredential.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/BackendSystemStatus.ts
- src/xpanse-api/generated/models/Response.ts
- src/xpanse-api/generated/services/AdminService.ts
fixed https://github.com/eclipse-xpanse/xpanse/issues/830
related https://github.com/eclipse-xpanse/xpanse/pull/833
Before:
After:
> Credential Center Using Active Csps

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/register/RegisterPanel.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/845
Before - 
after -
> change region  display in service details

- src/components/content/myServices/MyServices.tsx
- src/components/content/order/destroy/DestroyServiceStatusPolling.tsx
- src/components/content/order/migrate/MigrateService.tsx
- src/components/content/order/purge/PurgeServiceStatusPolling.tsx
- src/components/content/order/purge/usePurgeRequestSubmitQuery.ts
- src/styles/service_order.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/Response.ts
fixes [eclipse-xpanse/#816](https://github.com/eclipse-xpanse/xpanse/issues/816)
purge:
https://github.com/eclipse-xpanse/xpanse-ui/assets/42802200/de4e6b2b-ec59-46f1-8663-f7f4ea4ec638
> update destroy button and Popconfirm's default value.

- src/components/layouts/header/HeaderUserRoles.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/858
after fix on first render in prod mode -
> fix initial rendering of roles menu

- src/components/content/myServices/MyServiceDetails.tsx
- src/components/content/order/create/OrderSubmit.tsx
> remove debug logs

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/catalog/services/details/ShowIcon.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
Fixed eclipse-xpanse/xpanse#879
> ISV catalog view missing namespace information

- src/components/content/myServices/DeploymentResultMessage.tsx
- src/components/content/myServices/MyServiceDetails.tsx
- src/components/content/myServices/MyServices.tsx
- src/components/content/myServices/ServiceDetailsContent.tsx
- src/styles/my_services.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/874
> handle overflow in case of long deployment result messages.

- src/components/content/myServices/MyServices.tsx
- src/styles/my_services.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/AbstractCredentialInfo.ts
- src/xpanse-api/generated/models/CloudServiceProvider.ts
- src/xpanse-api/generated/models/CreateCredential.ts
- src/xpanse-api/generated/models/CreateRequest.ts
- src/xpanse-api/generated/models/CredentialVariables.ts
- src/xpanse-api/generated/models/ServiceDetailVo.ts
- src/xpanse-api/generated/models/ServiceTemplateVo.ts
- src/xpanse-api/generated/models/ServiceVo.ts
- src/xpanse-api/generated/models/UserAvailableServiceVo.ts
- src/xpanse-api/generated/services/AdminService.ts
- src/xpanse-api/generated/services/CredentialsManagementService.ts
- src/xpanse-api/generated/services/ServiceCatalogService.ts
- src/xpanse-api/generated/services/ServiceService.ts
- src/xpanse-api/generated/services/ServiceVendorService.ts
fixes eclipse-xpanse/xpanse#860
> fix myServices scroll for smaller screens.

- src/components/content/myServices/MyServices.tsx
fixes eclipse-xpanse/xpanse#885
> Add service creation date to My services table.

- src/components/content/order/migrate/MigrateServiceStatusPolling.tsx
- src/components/content/order/orderStatus/ProcessingStatus.tsx
fixes eclipse-xpanse/xpanse#886
> update migration final result display.

- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/unregister/UnregisterService.tsx
fixes eclipse-xpanse/xpanse#883
https://github.com/eclipse-xpanse/xpanse-ui/assets/42802200/953b82e8-9928-475d-9f8e-6452721304a1
> update service unregister.

- package.json
- src/components/content/catalog/services/update/UpdateService.tsx
- src/components/content/common/doc/ApiDoc.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/credential/CredentialApiDoc.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/migrate/ShowDeploy.tsx
- src/components/content/order/purge/PurgeServiceStatusPolling.tsx
- src/components/content/register/RegisterPanel.tsx
- src/components/content/systemStatus/HealthCheckStatus.tsx
close https://github.com/eclipse-xpanse/xpanse/issues/916
> enable eslint rule to detect any console logs

- .github/workflows/ui-release.yml
- package-lock.json
- package.json
related to https://github.com/eclipse-xpanse/xpanse/issues/922
> implement release job

- .github/workflows/ui-release.yml
- .gitignore
- package-lock.json
- package.json
> fix release build

- src/components/content/login/Logout.tsx
- src/components/content/order/create/CreateService.tsx
- src/components/content/order/create/NavigateOrderSubmission.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/formElements/GoToSubmit.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/928
> redirect to home page when no order state is available

- package.json
fixes https://github.com/eclipse-xpanse/xpanse/issues/935
> remove merge commit from changelog

- public/index.html
write page title in all smaller case to match the logo and pages
> fix page title format

- src/components/content/order/services/Services.tsx
remove redundant useEffect calls which are not required when using react-query
> remove redundant useEffect

- src/components/content/catalog/services/tree/CategoryCatalog.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/939
> fix empty tree rendering issue

- src/components/content/order/purge/PurgeServiceStatusPolling.tsx
this was a wrong commit. Must be removed.
> remove notification alert from purge

- src/components/content/myServices/MyServices.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/949
> disable parallel requests for destroy, purge and migrate

- src/components/content/order/create/CreateService.tsx
- src/components/content/order/formElements/CommonTypes.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/index.ts
- src/xpanse-api/generated/models/FlavorBasic.ts
- src/xpanse-api/generated/models/UserOrderableServiceVo.ts
fixed https://github.com/eclipse-xpanse/xpanse/issues/951
based on https://github.com/eclipse-xpanse/xpanse/pull/952
> Refactor Flavor data model

- scripts/generate_api_client.sh
related to eclipse-xpanse/xpanse#945
> add a script for api update

- package-lock.json
- package.json
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/formElements/CommonTypes.ts
- src/components/content/order/formElements/GoToSubmit.tsx
- src/components/content/order/formElements/NumberInput.tsx
- src/components/content/order/formElements/Switch.tsx
- src/components/content/order/formElements/TextInput.tsx
- src/components/content/order/migrate/ShowDeploy.tsx
- src/styles/service_order.css
fixes eclipse-xpanse/xpanse#902
> update form rules

- src/components/content/order/formElements/BooleanInput.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/972
> cache boolean form item

- src/components/content/myServices/MyServices.tsx
related https://github.com/eclipse-xpanse/xpanse/issues/971
> start polling only after request is accepted

- src/components/content/myServices/DeployedResourceProperties.tsx
- src/components/content/myServices/DeployedResources.tsx
- src/components/content/myServices/MyServices.tsx
- src/components/content/myServices/myServiceProps.tsx
- src/styles/my_services.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/974
> display deployed resource properties

- src/components/layouts/header/HeaderUserRoles.tsx
- src/components/layouts/sider/menuItems.ts
- src/components/protectedRoutes/ProtectedRoute.tsx
- src/components/utils/constants.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/984
> replace local storage with Zustand

- src/components/content/home/ServicesDashboard.tsx
- src/components/content/home/ServicesDashboardSkeleton.tsx
- src/components/content/myServices/MyServices.tsx
- src/components/content/myServices/MyServicesError.tsx
- src/components/utils/constants.tsx
- src/styles/my_services.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/983
> add dashboard to MyServices link.

- src/components/content/myServices/MyServices.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/990
> unify condition for allowing monitoring of services

- package-lock.json
> remove missing dependency

- src/components/content/home/ServicesDashboard.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/998
> display services dashboard even when no services are displayed

- src/App.tsx
- src/components/content/credential/AddCredential.tsx
- src/components/content/credential/Credential.tsx
- src/components/content/credential/UpdateCredential.tsx
- src/components/layouts/sider/menuItems.ts
- src/components/protectedRoutes/ProtectedRoute.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/Response.ts
- src/xpanse-api/generated/services/AdminService.ts
- src/xpanse-api/generated/services/AuthManagementService.ts
- src/xpanse-api/generated/services/CredentialsManagementService.ts
- src/xpanse-api/generated/services/MonitorService.ts
- src/xpanse-api/generated/services/PoliciesManagementService.ts
- src/xpanse-api/generated/services/ServiceCatalogService.ts
- src/xpanse-api/generated/services/ServiceService.ts
- src/xpanse-api/generated/services/ServiceVendorService.ts
- src/xpanse-api/generated/services/WorkFlowService.ts
Fixed eclipse-xpanse/xpanse#982
> Add option in UI to manage ISV credentials

- src/components/content/credential/AddCredential.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/formElements/CommonTypes.ts
- src/components/content/order/formElements/GoToSubmit.tsx
- src/components/content/order/migrate/ShowDeploy.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/OpenAPI.ts
- src/xpanse-api/generated/models/DeployRequest.ts
- src/xpanse-api/generated/models/MigrateRequest.ts
- src/xpanse-api/generated/models/Ocl.ts
- src/xpanse-api/generated/models/ServiceDetailVo.ts
- src/xpanse-api/generated/models/ServiceTemplateDetailVo.ts
- src/xpanse-api/generated/models/ServiceVo.ts
- src/xpanse-api/generated/models/UserOrderableServiceVo.ts
- src/xpanse-api/generated/services/CredentialsManagementService.ts
- src/xpanse-api/generated/services/PoliciesManagementService.ts
related to https://github.com/eclipse-xpanse/xpanse/issues/1001
> compile API changes for introducing service hosting type

- src/App.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1006
> Allow credentials page for user and isv roles

- src/components/content/common/ocl/DisplayOclData.tsx
related to eclipse-xpanse/xpanse#1001
> show service hosting information in register and update

- src/components/content/order/services/Services.tsx
- src/components/content/order/services/UserServiceDisplayType.ts
- src/components/content/order/services/userServiceHelper.ts
- src/components/layouts/sider/menuItems.ts
- src/components/layouts/sider/servicesMenu.tsx
related to eclipse-xpanse/xpanse#1001
> remove useEffect for loading services

- src/components/layouts/sider/LayoutSider.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1020
> menu selection to match page route

- src/components/content/credential/AddCredential.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/AbstractCredentialInfo.ts
- src/xpanse-api/generated/models/CredentialVariable.ts
- src/xpanse-api/generated/models/CredentialVariables.ts
- src/xpanse-api/generated/services/CredentialsManagementService.ts
- src/xpanse-api/generated/services/ServiceService.ts
Fixed eclipse-xpanse/xpanse#1009
> update request URI for end user credentials management

- src/components/content/myServices/MyServiceStatus.tsx
- src/components/content/myServices/MyServices.tsx
- src/components/content/myServices/MyServicesHostingType.tsx
related to https://github.com/eclipse-xpanse/xpanse/issues/1001
> add service hosting type to myservices table

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/catalog/services/details/ServiceHostingOptions.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/order/create/CreateService.tsx
- src/components/content/order/create/ServiceHostingSelection.tsx
- src/styles/catalog.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/1001
https://github.com/eclipse-xpanse/xpanse-ui/assets/54129659/e8802def-fb76-45ce-afe1-88ce8e5cff46
> add service hosting type to isv catalog view

- src/App.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1035
> add key to route list

- src/components/layouts/header/useCurrentRoleStore.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/1036
https://github.com/eclipse-xpanse/xpanse-ui/assets/54129659/f2d29067-25b7-4d7b-8765-05e15c06bf53
> store role information in localstorage via Zustand

- src/components/content/order/create/CreateService.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1046
https://github.com/eclipse-xpanse/xpanse-ui/assets/54129659/56958e5a-e856-48ce-9d8b-e37ed45dbb81
> handle state reset

- src/components/content/order/create/GoToSubmit.tsx
- src/components/content/order/services/Services.tsx
- src/components/layouts/sider/LayoutSider.tsx
- src/components/utils/constants.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1052
https://github.com/eclipse-xpanse/xpanse-ui/assets/54129659/a1b8ac5a-76fe-45c7-8722-d8f39c6adb53
> unify new order URLs

- src/components/content/credentials/AddCredential.tsx
- src/components/content/credentials/Credentials.tsx
- src/components/content/credentials/UpdateCredential.tsx
- src/components/content/credentials/query/queryCredentialsList.ts
Fixed eclipse-xpanse/xpanse#1029
> remove react-query passed as component properties

- src/styles/my_services.css
Fixed eclipse-xpanse/xpanse#1055
> Service successfully deployed alert - link not shown on mouse hover

- jest.config.json
- package-lock.json
- package.json
- src/components/content/home/Home.tsx
- src/components/content/home/isv/IsvServicesDashBoard.tsx
- src/components/content/home/isv/IsvServicesDashBoardError.tsx
- src/components/content/home/isv/IsvServicesDashBoardSkeleton.tsx
- src/components/content/home/isv/useListRegisteredServicesQuery.tsx
- src/components/content/home/user/EndUserServicesDashboard.tsx
- src/components/content/home/user/EndUserServicesDashboardError.tsx
- src/components/content/home/user/EndUserServicesDashboardSkeleton.tsx
- src/components/content/myServices/query/useListDeployedServiceByIsvQuery.tsx
- src/styles/credential.css
- src/styles/dashboard.css
- src/styles/health_status.css
- src/styles/monitor.css
- src/styles/my_services.css
- src/styles/policies.css
- src/styles/register.css
- src/styles/service_order.css
fixes eclipse-xpanse/xpanse#993
> add dashboard for isv.

- src/xpanse-api/api.json
- src/xpanse-api/generated/services/ServiceService.ts
Fixed eclipse-xpanse/xpanse#1063
> fix URIs for service details related services

- package-lock.json
- package.json
- src/components/content/order/common/ServiceHostingSelection.tsx
update typescript eslint for supporting TS 5.3
> update typescript-eslint plugin versions

- src/components/content/order/common/FlavorInfo.tsx
- src/components/content/order/common/RegionInfo.tsx
- src/components/content/order/create/CreateService.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/SelectDestination.tsx
fixes eclipse-xpanse/xpanse#1053
> display region and flavor drop downs as mandatory.

- package-lock.json
- package.json
> update knip to v3

- src/components/content/catalog/services/details/ServiceHostingOptions.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/components/content/catalog/services/unregister/UnregisterService.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
- src/components/utils/constants.tsx
fixes eclipse-xpanse/xpanse#1061
> ISV catalog refresh must bring control back to previously selected service.

- src/components/content/catalog/services/tree/CategoryCatalog.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1139
https://github.com/eclipse-xpanse/xpanse-ui/assets/54129659/dec8ea3a-a113-4336-98c9-f104fda2d0d8
> handle reload of category component

- src/components/content/deployedServices/common/DeployedServicesRunningStatus.tsx
- src/components/content/deployedServices/common/useServiceStateRestartQuery.ts
- src/components/content/deployedServices/common/useServiceStateStartQuery.ts
- src/components/content/deployedServices/common/useServiceStateStopQuery.ts
- src/components/content/deployedServices/myServices/MyServices.tsx
Fixed eclipse-xpanse/xpanse#1141
> provide option to start-stop services on the UI

- src/components/content/catalog/services/details/ServiceProvider.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1185
> fix service policies rerender issue

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/catalog/services/details/ServiceHostingOptions.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/policies/ServicePolicies.tsx
- src/components/content/catalog/services/unregister/UnregisterService.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
- src/styles/catalog.css
- src/styles/service_policies.css
fixes eclipse-xpanse/xpanse#1175
> update catalog btn.

- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/policies/ServicePolicies.tsx
- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/components/content/catalog/services/unregister/UnregisterService.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1212
> fix refresh issues in service catalog

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/create/OrderSubmitStatusPolling.tsx
- src/components/content/order/migrate/MigrateServiceStatusPolling.tsx
fixes eclipse-xpanse/xpanse#1092
> handle new failure status ROLLBACK_FAILED.

- src/components/content/register/RegisterPanel.tsx
- src/components/content/register/RegisterResult.tsx
- src/styles/register.css
fixes eclipse-xpanse/xpanse#1099
> add more options to handle errors in service registration.

- src/components/content/common/ocl/ContactDetailsText.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
fixes eclipse-xpanse/xpanse#1257
> add service provider contact details on UI.

- src/components/content/catalog/services/details/ServiceProvider.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1275
> rerender service detail on version change

- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/useMigrateServiceQuery.ts
Fixed #eclipse-xpanse/xpanse#1283
> update service migrate ui

- src/components/content/catalog/services/details/ServiceDetail.tsx
related to eclipse-xpanse/xpanse#1257
> update contact details.

- docker/nginx-entrypoint.sh
fixes https://github.com/eclipse-xpanse/xpanse/issues/1303
> fix path to OidcTrustedDomains.js file in docker image

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/destroy/DestroyServiceStatusPolling.tsx
- src/components/content/order/purge/PurgeServiceStatusPolling.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1289
> update service deployment status directly on UI for better UX

- src/App.tsx
- src/components/content/workflows/Workflows.tsx
- src/components/content/workflows/WorkflowsTip.tsx
- src/components/content/workflows/query/useAllTasksQuery.ts
- src/components/layouts/sider/menuItems.ts
- src/components/layouts/sider/servicesMenu.tsx
- src/components/utils/constants.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/index.ts
- src/xpanse-api/generated/models/UserOrderableServiceVo.ts
- src/xpanse-api/generated/models/WorkFlowTask.ts
- src/xpanse-api/generated/services/WorkFlowService.ts
Fixed eclipse-xpanse/xpanse#1233
> add new component to show workflow tasks assigned to user

- src/components/content/deployedServices/common/DeployedServicesRunningStatus.tsx
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/myServices/query/useServiceStateRestartQuery.ts
- src/components/content/deployedServices/myServices/query/useServiceStateStartQuery.ts
- src/components/content/deployedServices/myServices/query/useServiceStateStopQuery.ts
- src/styles/my_services.css
Fixed eclipse-xpanse/xpanse#1312
> show the lastStartedAt and lastStoppedAt time in MyServices

- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/policies/AddOrUpdateServicePolicy.tsx
- src/components/content/catalog/services/policies/ServicePolicies.tsx
- src/components/content/catalog/services/policies/servicePoliciesParams.ts
- src/styles/service_policies.css
fixes eclipse-xpanse/xpanse#1274
> update service flavors.

- src/components/content/login/Logout.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1374
> fix logout redirect URI from catalog page

- package-lock.json
- package.json
- src/components/content/credentials/AddCredential.tsx
- src/components/content/credentials/CredentialTip.tsx
- src/components/content/credentials/Credentials.tsx
- src/components/content/credentials/UpdateCredential.tsx
- src/styles/credential.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/1376
> remove redundant useEffect from credentials component

- DEPENDENCIES
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/reports/Reports.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1377
> remove redundant useEffect from deployedServices component

- src/components/content/common/ocl/ContactDetailsText.tsx
- src/styles/register.css
fixes eclipse-xpanse/xpanse#1353
> Add icons in the software vendor contact details popover.

- src/xpanse-api/api.json
- src/xpanse-api/generated/index.ts
- src/xpanse-api/generated/models/AutoFill.ts
- src/xpanse-api/generated/models/DeployVariable.ts
Fixed eclipse-xpanse/xpanse#1337
> Extend OCL to provide auto-fill for deploy variables

- src/components/content/policies/AddOrUpdatePolicy.tsx
- src/components/content/policies/Policies.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1395
> remove redundant useEffect from policies component

- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/details/ServiceProviderSkeleton.tsx
- src/components/content/catalog/services/menu/CatalogMainMenu.tsx
- src/components/content/catalog/services/policies/ServicePolicies.tsx
- src/components/content/catalog/services/tree/CatalogFullView.tsx
- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/components/content/catalog/services/tree/ServiceTree.tsx
- src/components/content/catalog/services/unregister/UnregisterMutation.ts
- src/components/content/catalog/services/unregister/UnregisterResult.tsx
- src/components/content/catalog/services/unregister/UnregisterService.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
- src/components/content/common/catalog/catalogProps.ts
- src/components/layouts/sider/LayoutSider.tsx
- src/styles/catalog.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/1419
> remove redundant useEffect from catalog component

- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/useAutoFillDeployVariableQuery.ts
- src/components/content/order/formDataHelpers/deployParamsHelper.ts
- src/components/content/order/formElements/TextInput.tsx
- src/components/content/order/migrate/DeploymentForm.tsx
- src/components/content/order/types/DeployParam.ts
Fixed eclipse-xpanse/xpanse#1404
> implement auto-fill feature on UI

- package-lock.json
- src/components/content/common/ocl/ContactDetailsText.tsx
fixes eclipse-xpanse/xpanse#1423
> fix console error in ContactDetailsText component.

- src/App.tsx
- src/components/content/serviceReviews/ApproveOrRejectServiceTemplate.tsx
- src/components/content/serviceReviews/GetServiceTemplatesListError.tsx
- src/components/content/serviceReviews/ServiceReviews.tsx
- src/components/content/serviceReviews/ServiceReviewsDetails.tsx
- src/components/content/serviceReviews/ServiceTemplateRegisterStatus.tsx
- src/components/content/serviceReviews/query/useApproveOrRejectRequest.ts
- src/components/content/serviceReviews/query/useListAllServiceTemplatesQuery.ts
- src/components/layouts/sider/menuItems.ts
- src/components/layouts/sider/servicesMenu.tsx
- src/components/oidc/OidcConfig.ts
- src/components/protectedRoutes/ProtectedRoute.tsx
- src/components/utils/constants.tsx
- src/styles/service_review.css
fixes eclipse-xpanse/xpanse#1413
> add approval feature for CSP user.

- src/components/content/serviceReviews/ServiceReviews.tsx
- src/components/content/serviceReviews/ServiceReviewsDetails.tsx
- src/components/content/serviceReviews/query/useGetRegistrationDetails.ts
- src/styles/service_review.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/OpenAPI.ts
- src/xpanse-api/generated/models/ServiceTemplateDetailVo.ts
fixes eclipse-xpanse/xpanse#1436
> update approval feature for CSP user.

- src/components/content/credentials/AddCredential.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/ServiceTemplateDetailVo.ts
- src/xpanse-api/generated/services/AdminService.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/1433
related to https://github.com/eclipse-xpanse/xpanse/pull/1437
> update API to list active csps

- package-lock.json
- package.json
- src/components/content/catalog/services/menu/catalogMenu.tsx
- src/components/content/catalog/services/policies/ServicePolicySubmitResult.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/deployedServices/common/DeployedResourceProperties.tsx
- src/components/content/deployedServices/common/DeploymentResultMessage.tsx
- src/components/content/home/__tests__/Home.test.tsx
- src/components/content/order/create/GoToSubmit.tsx
- src/components/content/order/migrate/DeploymentForm.tsx
- src/components/content/order/orderStatus/OrderSubmitResultDetails.tsx
- src/components/content/order/services/ServicesSkeleton.tsx
- src/components/content/policies/PolicySubmitResultDetails.tsx
- src/components/content/register/registerPanelMenu.tsx
- src/components/utils/convertMapToDetailsList.tsx
fixes eclipse-xpanse/xpanse#1427
> fix warning.

- src/components/content/order/create/GoToSubmit.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formDataHelpers/deployParamsHelper.ts
- src/components/content/order/migrate/DeploymentForm.tsx
- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/DeployRequest.ts
- src/xpanse-api/generated/models/MigrateRequest.ts
Fixed eclipse-xpanse/xpanse#1435
related to eclipse-xpanse/xpanse#1458
> Extend DeployRequestBase class to have area information

- src/components/content/order/create/useAutoFillDeployVariableQuery.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/index.ts
- src/xpanse-api/generated/models/AvailabilityZoneConfig.ts
- src/xpanse-api/generated/models/DeployRequest.ts
- src/xpanse-api/generated/models/Deployment.ts
- src/xpanse-api/generated/models/MigrateRequest.ts
- src/xpanse-api/generated/models/UserOrderableServiceVo.ts
- src/xpanse-api/generated/services/CloudResourcesService.ts
- src/xpanse-api/generated/services/ServiceService.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/1441
related to https://github.com/eclipse-xpanse/xpanse/pull/1465
> update api client to support availability zones

- src/components/content/common/ocl/BillingText.tsx
- src/components/content/order/common/BillingInfo.tsx
- src/components/content/order/formDataHelpers/billingHelper.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/Billing.ts
- src/xpanse-api/generated/models/Response.ts
- src/xpanse-api/generated/services/ServiceService.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/1473
Based on https://github.com/eclipse-xpanse/xpanse/pull/1482
> update billing model of service

- src/components/content/workflows/Workflows.tsx
Fixed eclipse-xpanse/xpanse#1509
> UI-Workflows page parsing returned data error

- src/components/content/common/ocl/YamlSyntaxValidationResult.tsx
- src/components/content/register/RegisterPanel.tsx
- src/styles/register.css
Fixed eclipse-xpanse/xpanse#1537
> fix register button spacing

- src/components/content/review/ServiceReviews.tsx
- src/components/content/review/query/useListAllServiceTemplatesQuery.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/1596
> fix query key for CSP user's getServiceTemplates

- src/components/content/catalog/services/details/ShowIcon.tsx
- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/services/Services.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/styles/app.css
- src/styles/catalog.css
- src/styles/service_order.css
Fixed eclipse-xpanse/xpanse#1587
> Styling issues between deployment page service name and version

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/reports/Reports.tsx
- src/components/content/home/isv/IsvServicesDashBoard.tsx
- src/components/content/home/user/EndUserServicesDashboard.tsx
Fixed eclipse-xpanse/xpanse#1576
> dashboard to consider modification status as well

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/locks/Locks.tsx
- src/components/content/order/locks/LocksResult.tsx
- src/components/content/order/locks/useLockRequest.ts
- src/styles/locks.css
fixes eclipse-xpanse/xpanse#1566
> add locks for myServices.

- src/components/content/order/common/RegionInfo.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formDataHelpers/areaHelper.ts
- src/components/content/order/formDataHelpers/regionHelper.ts
- src/components/content/order/migrate/ExportServiceData.tsx
- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/migrate/SelectDestination.tsx
- src/components/content/order/migrate/SelectMigrationTarget.tsx
- src/components/content/order/types/MigrationSteps.ts
- src/components/content/order/types/RegionDropDownInfo.ts
- src/styles/service_order.css
Fixed eclipse-xpanse/xpanse#1579
> migration modal not to show same region again

- src/components/content/order/common/BillingInfo.tsx
- src/components/content/order/common/BillingModeSelection.tsx
- src/components/content/order/common/MigrateServiceSubmitBillingMode.tsx
- src/components/content/order/common/utils/OrderSubmitProps.ts
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formDataHelpers/billingHelper.ts
- src/components/content/order/formDataHelpers/deployParamsHelper.ts
- src/components/content/order/migrate/DeploymentForm.tsx
- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/SelectDestination.tsx
- src/components/content/order/migrate/SelectMigrationTarget.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/index.ts
- src/xpanse-api/generated/models/Billing.ts
- src/xpanse-api/generated/models/DeployRequest.ts
- src/xpanse-api/generated/models/MigrateRequest.ts
- src/xpanse-api/generated/models/Response.ts
- src/xpanse-api/generated/models/ServiceLockConfig.ts
Fixed eclipse-xpanse/xpanse#1592
related to eclipse-xpanse/xpanse#1607
> pricing changes to ISV and CSP role

- src/components/content/common/ocl/BillingText.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formDataHelpers/billingHelper.ts
- src/components/content/order/migrate/SelectDestination.tsx
- src/components/content/order/migrate/SelectMigrationTarget.tsx
- src/styles/app.css
Fixed eclipse-xpanse/xpanse#1610
> Show billing modes in ISV and CSP views

- src/components/content/order/common/availabilityzone/AvailabilityZoneError.tsx
- src/components/content/order/common/availabilityzone/AvailabilityZoneFormItem.tsx
- src/components/content/order/migrate/SelectDestination.tsx
Fixed eclipse-xpanse/xpanse#1611
> add "Retry" option when loading AZ fails

- src/components/content/order/common/utils/OrderSubmitProps.ts
- src/components/content/order/common/utils/ScaleOrModifyWarnings.ts
- src/components/content/order/modify/Modify.tsx
- src/components/content/order/scale/Scale.tsx
- src/styles/service_modify.css
fixes eclipse-xpanse/xpanse#1586
> add Warning for Modify and Scale.

- src/components/content/deployedServices/myServices/MyServiceHistory.tsx
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/myServices/query/useListServiceModifyHistoryQuery.ts
- src/styles/service-modify.module.css
Fixed eclipse-xpanse/xpanse#1632
> Show modification history details in UI

- src/components/layouts/sider/LayoutSider.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1660
> fix icon not loading on sub-pages

- src/components/content/order/common/BillingModeSelection.tsx
- src/components/content/order/common/FlavorFeatures.tsx
- src/components/content/order/common/FlavorSelection.tsx
- src/components/content/order/common/MigrateServiceSubmitAvailabilityZoneInfo.tsx
- src/components/content/order/common/MigrateServiceSubmitBillingMode.tsx
- src/components/content/order/common/RegionSelection.tsx
- src/components/content/order/common/ServiceHostingSelection.tsx
- src/components/content/order/common/availabilityzone/AvailabilityZoneFormItem.tsx
- src/components/content/order/create/NavigateOrderSubmission.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formElements/CspSelect.tsx
- src/components/content/order/migrate/DeploymentForm.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/SelectDestination.tsx
- src/styles/app.module.css
- src/styles/flavor.module.css
- src/styles/service-order.module.css
- src/styles/table.module.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/1659
> refactor order and migrate forms

- src/components/content/monitor/Monitor.tsx
- src/components/content/monitor/MonitorChart.tsx
- src/components/content/monitor/MonitorTip.tsx
Fixed eclipse-xpanse/xpanse#1643
> add retry to monitor failure alert

- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/unregister/UnregisterMutation.ts
- src/components/content/catalog/services/unregister/UnregisterService.tsx
- src/components/content/order/common/FlavorPrice.tsx
related to https://github.com/eclipse-xpanse/xpanse/issues/1655
> fix unregister alert not being removed on rerender

- src/components/content/catalog/services/update/UpdateService.tsx
Fixed eclipse-xpanse/xpanse#1651
> service update buttons still floating when file name is big

- src/components/content/catalog/services/delete/DeleteResult.tsx
- src/components/content/catalog/services/delete/DeleteService.tsx
- src/components/content/catalog/services/delete/DeleteServiceMutation.ts
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/re-register/ReRegisterMutation.ts
- src/components/content/catalog/services/re-register/ReRegisterResult.tsx
- src/components/content/catalog/services/re-register/ReRegisterService.tsx
Fixed eclipse-xpanse/xpanse#1655
> add re-regsiter and delete options to service catalog

- src/components/content/catalog/services/details/ServiceDetail.tsx
fixes eclipse-xpanse/xpanse#1436
> show service template ID in the ISV catalog view.

- src/components/content/catalog/services/details/ServiceDetail.tsx
related to  https://github.com/eclipse-xpanse/xpanse/issues/1436
> update service template id.

- src/components/content/order/common/MigrateServiceSubmitAvailabilityZoneInfo.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
Fixed eclipse-xpanse/xpanse#1665
> AZ data not shown in final migration page when AZ not selected

- src/components/content/order/common/FlavorFeatures.tsx
- src/components/content/order/common/FlavorPrice.tsx
- src/components/content/order/common/FlavorPriceRetry.tsx
- src/components/content/order/common/FlavorSelection.tsx
- src/components/content/order/common/FlavorTitle.tsx
- src/components/content/order/common/useGetServicePricesQuery.ts
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formDataHelpers/flavorHelper.ts
- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/SelectDestination.tsx
- src/components/content/order/scale/Scale.tsx
- src/components/content/order/types/ServiceFlavorWithPrice.ts
- src/styles/flavor.module.css
- src/styles/service-modify.module.css
fixes eclipse-xpanse/xpanse#1663
> display price.

- src/components/content/order/migrate/DeploymentForm.tsx
- src/components/content/order/migrate/Migrate.tsx
Fixed eclipse-xpanse/xpanse#1664
> EULA flag works only after unchecking and checking again in migration

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/common/ocl/FlavorsText.tsx
- src/components/content/review/ServiceReviews.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/styles/ocl-display.module.css
fixes eclipse-xpanse/xpanse#1669
> update flavor view in service catalog views.

- src/components/content/common/ocl/ContactDetailsText.tsx
- src/components/content/order/formDataHelpers/getAvailabilityZoneRequirementsForAService.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/models/AvailabilityZoneConfig.ts
- src/xpanse-api/generated/models/Billing.ts
- src/xpanse-api/generated/models/CloudServiceProvider.ts
- src/xpanse-api/generated/models/CreateCredential.ts
- src/xpanse-api/generated/models/CredentialVariable.ts
- src/xpanse-api/generated/models/DeployVariable.ts
- src/xpanse-api/generated/models/Deployment.ts
- src/xpanse-api/generated/models/FlavorsWithPrice.ts
- src/xpanse-api/generated/models/Region.ts
- src/xpanse-api/generated/models/ServiceFlavorWithPrice.ts
- src/xpanse-api/generated/models/ServiceLockConfig.ts
- src/xpanse-api/generated/models/ServiceProviderContactDetails.ts
- src/xpanse-api/generated/models/UserOrderableServiceVo.ts
- src/xpanse-api/generated/services/ServiceService.ts
Based on https://github.com/eclipse-xpanse/xpanse/pull/1702 and https://github.com/eclipse-xpanse/xpanse/pull/1707
> update api client

- src/components/content/deployedServices/myServices/MyServices.tsx
Fixed  Fixed eclipse-xpanse/xpanse#1689
> UI-Purge modification failed services always failed.

- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/deployedServices/common/DeployedServicesHostingType.tsx
- src/components/content/review/ServiceReviews.tsx
Fixed eclipse-xpanse/xpanse#1684
> Add 'service hosting type' column to review service table

- src/App.tsx
- src/components/content/common/registeredServices/registeredServiceProps.ts
- src/components/content/registeredServices/RegisteredServices.tsx
- src/components/content/registeredServices/tree/RegisteredServicesFullView.tsx
- src/components/content/registeredServices/tree/RegisteredServicesTree.tsx
- src/components/content/registeredServices/tree/ServiceContent.tsx
- src/components/layouts/sider/menuItems.ts
- src/components/layouts/sider/servicesMenu.tsx
- src/components/utils/constants.tsx
fixes eclipse-xpanse/xpanse#1685
> Add service catalog to CSP role.

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/deployedServices/myServices/query/useDeployedServiceByIsvQuery.tsx
- src/components/content/deployedServices/reports/Reports.tsx
- src/styles/catalog.module.css
Fixed eclipse-xpanse/xpanse#1681
> Add services deployed information to each service in service catalog

- src/components/content/order/common/FlavorSelection.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/SelectDestination.tsx
Fixed eclipse-xpanse/xpanse#1749
> Next button not handled correctly

- src/components/content/review/ApproveOrRejectServiceTemplate.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/components/content/review/query/useApproveOrRejectRequest.ts
Fixed eclipse-xpanse/xpanse/issues/1703
> review service buttons remains disabled if the service is again sent for approval

- src/components/content/catalog/services/update/UpdateResult.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
Fixed eclipse-xpanse/xpanse#1762
https://github.com/eclipse-xpanse/xpanse-ui/assets/122504203/0487dee4-4cb1-4cbc-b4d9-12a477571913
> try again button in update service alert is not correct

- src/components/content/policies/AddOrUpdatePolicy.tsx
Fixed eclipse-xpanse/xpanse#1761
> policies component shows all CSPs instead of just the active one

- src/components/content/catalog/services/delete/DeleteService.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/re-register/ReRegisterService.tsx
Fixed eclipse-xpanse/xpanse#1764
> warning in console log on re-registering service

- src/components/content/order/common/availabilityzone/AvailabilityZoneError.tsx
- src/components/content/order/common/availabilityzone/AvailabilityZoneFormItem.tsx
- src/styles/service-order.module.css
Fixed eclipse-xpanse/xpanse#1767
> Update error alert when AZ loading fails and AZ is not mandatory field

- src/components/content/deployedServices/myServices/MyServices.tsx
Fixed eclipse-xpanse/xpanse#1782
> After the service modification successful, it cannot be destroyed

- src/components/content/deployedServices/myServices/MyServiceHistory.tsx
- src/components/content/deployedServices/myServices/query/useListServiceModifyHistoryQuery.ts
- src/components/content/deployedServices/reports/query/useGetServiceDetailsByIdForIsvQuery.ts
- src/components/content/order/common/modifySubmitRequest.ts
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/destroy/useDestroyRequestSubmitQuery.ts
- src/components/content/order/locks/Locks.tsx
- src/components/content/order/locks/useLockRequest.ts
- src/components/content/order/migrate/useMigrateServiceQuery.ts
- src/components/content/order/modify/Modify.tsx
- src/components/content/order/orderStatus/useServiceDetailsPollingQuery.ts
- src/components/content/order/purge/usePurgeRequestStatusQuery.ts
- src/components/content/order/purge/usePurgeRequestSubmitQuery.ts
- src/components/content/order/scale/Scale.tsx
- src/components/content/order/serviceState/useServiceDetailsByServiceStatePollingQuery.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/ApiRequestOptions.ts
- src/xpanse-api/generated/core/OpenAPI.ts
- src/xpanse-api/generated/core/request.ts
- src/xpanse-api/generated/services.gen.ts
- src/xpanse-api/generated/types.gen.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/1723
Based on https://github.com/eclipse-xpanse/xpanse/pull/1779
> update service manage apis

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/common/ocl/FlavorsText.tsx
- src/components/content/order/common/FlavorSelection.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formDataHelpers/flavorHelper.ts
- src/components/content/order/scale/Scale.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/styles/flavor.module.css
- src/styles/ocl-display.module.css
fixes eclipse-xpanse/xpanse#1626
scale:
order:
migrate:
https://github.com/eclipse-xpanse/xpanse-ui/assets/42802200/7e3ddcd9-ac86-476a-a31b-af4b95a1fe8d
updated:
catalog:
review:
registered service:
register:
> add flavor priority.

- src/components/content/deployedServices/common/DeployedResourceProperties.tsx
- src/components/content/deployedServices/common/DeployedResources.tsx
- src/components/content/deployedServices/myServices/myServiceProps.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/services.gen.ts
- src/xpanse-api/generated/types.gen.ts
Based on https://github.com/eclipse-xpanse/xpanse/pull/1802
> update deploy resource data

- src/components/content/home/isv/IsvServicesDashBoard.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1814
> fix retry for ISV dashboard alert

- src/components/content/order/common/utils/groupServicesByLatestVersion.ts
- src/components/content/order/query/userOrderableServicesQuery.ts
- src/components/content/order/services/Services.tsx
- src/components/content/order/services/UserServiceLatestVersionDisplayType.ts
- src/components/layouts/header/HeaderUserRoles.tsx
- src/components/layouts/header/LayoutHeader.tsx
- src/components/layouts/header/SearchServices.tsx
- src/styles/header.module.css
- src/styles/search-services.module.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/1817
> add search services feature

- src/components/content/catalog/services/details/ServiceDetail.tsx
Fixed eclipse-xpanse/xpanse#1789
> active deployment services must not be shown for CSP user

- src/components/content/order/common/availabilityzone/AvailabilityZoneError.tsx
- src/components/content/order/common/availabilityzone/AvailabilityZoneFormItem.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/styles/service-order.module.css
Fixed eclipse-xpanse/xpanse#1821
> display issues with AZ in new order

- src/components/content/common/ocl/FlavorsText.tsx
Fixed eclipse-xpanse/xpanse#1836
> fix spacing of different blocks in register panel

- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/SelectDestination.tsx
Fixed eclipse-xpanse/xpanse#1787
> make migrate flavors can be changable when select destination.

- src/App.tsx
- src/components/utils/constants.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1853
> disable retries for all final HTTP errors

- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/migrate/MigrationProcessingStatus.tsx
- src/components/content/order/orderStatus/OrderSubmitStatusAlert.tsx
- src/components/content/order/orderStatus/ProcessingStatus.tsx
Fixed eclipse-xpanse/xpanse#1766
> Error Alert for service-vendor hosted services must have additional info

- src/components/content/order/create/SelectServiceForm.tsx
Fixed eclipse-xpanse/xpanse#1765
> issue with changing service hosting type when flavors are different

- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/re-register/ReRegisterResult.tsx
- src/components/content/catalog/services/re-register/ReRegisterService.tsx
- src/components/content/catalog/services/update/UpdateResult.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
- src/components/content/register/RegisterPanel.tsx
- src/components/content/register/RegisterResult.tsx
Fixed eclipse-xpanse/xpanse#1661
> change alert msg for service registration and service updaten based on status

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/common/ScaleOrModifyOrderSubmitResult.tsx
- src/components/content/order/common/ScaleOrModifySubmitStatusAlert.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/orderStatus/OrderSubmitResult.tsx
- src/components/content/order/orderStatus/OrderSubmitStatusAlert.tsx
- src/components/content/order/orderStatus/ProcessingStatus.tsx
- src/components/content/order/orderStatus/useServiceDetailsPollingQuery.ts
- src/components/content/order/retryDeployment/useRedeployFailedDeploymentQuery.ts
- src/components/content/review/ServiceReviewsDetails.tsx
Fixed #eclipse-xpanse/xpanse#1694
> Add retry option to deployed services

- src/components/content/order/create/SelectServiceForm.tsx
Fixed eclipse-xpanse/xpanse#1861
> Call the service getPricesByService with the billingMode unsupported by the service template

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/common/BillingModeSelection.tsx
- src/components/content/order/common/FlavorSelection.tsx
- src/components/content/order/common/MigrateServiceSubmitAvailabilityZoneInfo.tsx
- src/components/content/order/common/MigrateServiceSubmitBillingMode.tsx
- src/components/content/order/common/RegionSelection.tsx
- src/components/content/order/common/ServiceHostingSelection.tsx
- src/components/content/order/common/availabilityzone/AvailabilityZoneFormItem.tsx
- src/components/content/order/formElements/CspSelect.tsx
- src/components/content/order/formElements/VersionSelect.tsx
- src/styles/service-order.module.css
Fixed eclipse-xpanse/xpanse#1857
> Order screen overlapping fields on smaller screens

- src/components/content/catalog/services/tree/CatalogFullView.tsx
- src/components/content/catalog/services/tree/ServiceTree.tsx
- src/components/content/common/tree/filterTreeData.ts
- src/components/content/registeredServices/tree/RegisteredServicesFullView.tsx
- src/components/content/registeredServices/tree/RegisteredServicesTree.tsx
- src/styles/catalog.module.css
Fixed eclipse-xpanse/xpanse#1858
> add search to the services tree in ISV and CSP view

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/credentials/AddCredential.tsx
- src/components/content/credentials/Credentials.tsx
- src/components/content/credentials/UpdateCredential.tsx
- src/components/content/order/common/availabilityzone/AvailabilityZoneFormItem.tsx
- src/components/content/order/common/utils/OrderItem.tsx
- src/components/content/order/common/utils/useGetAvailabilityZonesForRegionQuery.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/create/useAutoFillDeployVariableQuery.ts
- src/components/content/order/formElements/TextInput.tsx
- src/components/content/order/formElements/VersionSelect.tsx
- src/components/content/order/migrate/DeploymentForm.tsx
- src/components/content/order/migrate/SelectDestination.tsx
- src/components/content/order/modify/Modify.tsx
- src/components/content/order/scale/Scale.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/CancelablePromise.ts
- src/xpanse-api/generated/services.gen.ts
- src/xpanse-api/generated/types.gen.ts
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1849
Based on https://github.com/eclipse-xpanse/xpanse/pull/1915
> Credentials add field 'site'

- src/components/content/login/Logout.tsx
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1930
Related to  https://github.com/eclipse-xpanse/xpanse-iam/pull/22
https://github.com/user-attachments/assets/4de92524-2ccd-436c-a54c-0fae1a57125e
> Fix page registeredServices authorized error

- src/components/content/monitor/MetricQueries.ts
- src/components/content/monitor/MonitorChart.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/1924
> fix monitor charts not rerendering issue

- src/components/content/common/ocl/RegionText.tsx
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1925
> fix the problem when region is empty.

- src/components/content/deployedServices/myServices/MyServiceHistory.tsx
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1935
> fill ModifyId in Service Modified History

- src/components/content/deployedServices/myServices/query/useGetOrderableServiceDetails.tsx
- src/components/content/order/formDataHelpers/flavorHelper.ts
- src/components/content/order/modify/Modify.tsx
- src/components/content/order/scale/Scale.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/services.gen.ts
- src/xpanse-api/generated/types.gen.ts
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1936
Scale for end user:
Modify for end user:
Migrate for end user:
> update myservices of modify, scale api for end user.

- src/components/content/deployedServices/myServices/MyServices.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2001
> remove duplicate alerts

- src/components/content/common/ocl/DeploymentText.tsx
- src/components/content/review/ServiceReviews.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/services.gen.ts
- src/xpanse-api/generated/types.gen.ts
related to https://github.com/eclipse-xpanse/xpanse/issues/2010
> generate latest xpanse API client

- src/components/content/common/ocl/DeploymentText.tsx
- src/components/content/deployedServices/myServices/query/useListServiceModifyHistoryQuery.ts
- src/components/content/order/formDataHelpers/getAvailabilityZoneRequirementsForAService.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/services.gen.ts
- src/xpanse-api/generated/types.gen.ts
related to https://github.com/eclipse-xpanse/xpanse/pull/2035
> rename method and fields in API

- src/components/content/order/orderStatus/OrderSubmitResultDetails.tsx
- src/styles/submit-alert.module.css
- src/styles/submit-result.module.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/2074
> Make big error alerts fit within the viewport.

- src/components/content/common/latestServiceOrderStatusQuery/useLatestServiceOrderStatusQuery.ts
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/migrate/MigrateServiceStatusAlert.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/MigrationProcessingStatus.tsx
- src/components/content/order/migrate/useMigrateServiceQuery.ts
- src/components/content/order/orderStatus/useServiceDetailsPollingQuery.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/OpenAPI.ts
- src/xpanse-api/generated/services.gen.ts
- src/xpanse-api/generated/types.gen.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2086
migrate success:
migrate request failed:
migrate-when-deploy-failed:
migrate-when-destroy-failed:
> update migrate polling status.

- src/components/content/catalog/services/delete/DeleteService.tsx
- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/re-register/ReRegisterResult.tsx
- src/components/content/catalog/services/re-register/ReRegisterService.tsx
- src/components/content/catalog/services/unregister/UnregisterService.tsx
- src/components/content/catalog/services/update/UpdateResult.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
- src/components/content/common/catalog/ServiceTemplateRegisterStatus.tsx
- src/components/content/home/isv/useListRegisteredServicesQuery.tsx
- src/components/content/order/migrate/Migrate.tsx
- src/components/content/order/query/userOrderableServicesQuery.ts
- src/components/content/register/RegisterPanel.tsx
- src/components/content/register/RegisterResult.tsx
- src/components/content/review/ServiceReviews.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/components/content/review/query/useListAllServiceTemplatesQuery.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/OpenAPI.ts
- src/xpanse-api/generated/services.gen.ts
- src/xpanse-api/generated/types.gen.ts
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2098 and https://github.com/eclipse-xpanse/xpanse/issues/2104
Based on https://github.com/eclipse-xpanse/xpanse/pull/2118
> Refactor service template data

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/destroy/DestroyServiceStatusAlert.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2081
releated https://github.com/eclipse-xpanse/xpanse/issues/2080
error msg saved to table:
destroy failed:
destroy successfully:
> update destroy polling status.

- src/components/content/catalog/services/query/useAvailableServiceTemplatesQuery.ts
- src/components/content/deployedServices/myServices/query/useGetOrderableServiceDetails.tsx
- src/components/content/deployedServices/myServices/query/useGetOrderableServiceDetailsQuery.ts
- src/components/content/home/isv/useListRegisteredServicesQuery.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
Based on https://github.com/eclipse-xpanse/xpanse/pull/2154
> update apis of query service templates

- src/components/content/order/common/availabilityzone/AvailabilityZoneError.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2165
> show API error information when AZ is optional

- src/components/content/review/ServiceReviews.tsx
fixes https://github.com/eclipse-xpanse/xpanse/pull/2174
> remove csp from review.

- package-lock.json
- package.json
- src/components/content/order/common/availabilityzone/AvailabilityZoneError.tsx
- src/components/content/order/common/availabilityzone/AvailabilityZoneFormItem.tsx
- src/components/content/order/common/utils/useGetAvailabilityZonesForRegionQuery.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/migrate/SelectDestination.tsx
- src/components/content/review/ServiceReviews.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
related to https://github.com/eclipse-xpanse/xpanse/issues/2160
> pass service template ID also for fetching availability zones

- src/components/content/deployedServices/myServices/MyServiceHistory.tsx
- src/components/content/deployedServices/myServices/MyServiceHistoryDetails.tsx
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/myServices/query/useListServiceModifyHistoryQuery.ts
- src/styles/service-modify.module.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
fixes https://github.com/eclipse-xpanse/xpanse/pull/2030
> add order history.

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/myServices/query/useGetOrderableServiceDetailsQuery.ts
Fixed eclipse-xpanse/xpanse#2109
> MyServices to use getOrderdableServiceDetailsByServiceId service

- src/components/content/catalog/services/delete/DeleteServiceMutation.ts
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/re-register/ReRegisterMutation.ts
- src/components/content/catalog/services/re-register/ReRegisterResult.tsx
- src/components/content/catalog/services/re-register/ReRegisterService.tsx
- src/components/content/catalog/services/unregister/UnregisterMutation.ts
- src/components/content/catalog/services/update/UpdateService.tsx
- src/components/content/deployedServices/myServices/query/useGetOrderableServiceDetails.tsx
- src/components/content/register/RegisterPanel.tsx
- src/components/content/review/ApproveOrRejectServiceTemplate.tsx
- src/components/content/review/ServiceReviews.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/components/content/review/query/useApproveOrRejectRequest.ts
- src/components/content/review/query/useGetPendingServiceReviewRequestQuery.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
Fixed eclipse-xpanse/xpanse#2112
> Changes to review service of CSP

- src/components/content/catalog/services/delete/DeleteServiceMutation.ts
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/re-register/ReRegisterService.tsx
- src/components/content/order/common/IsvNameDisplay.tsx
- src/components/content/order/common/utils/OrderSubmitProps.ts
- src/components/content/order/common/utils/groupServicesByLatestVersion.ts
- src/components/content/order/create/CreateService.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formDataHelpers/deployParamsHelper.ts
- src/components/content/order/formDataHelpers/serviceNamespaceHelper.ts
- src/components/content/order/services/Services.tsx
- src/components/content/order/services/UserServiceLatestVersionDisplayType.ts
- src/styles/service-order.module.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/types.gen.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2117
add contact details:
add tag for isv:
updated isv for order:
> show isv for end user.

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/catalog/services/re-register/ReRegisterMutation.ts
- src/components/content/catalog/services/unregister/UnregisterMutation.ts
- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/common/registeredServices/registeredServiceProps.ts
- src/components/content/order/common/IsvNameDisplay.tsx
- src/components/content/order/common/utils/OrderSubmitProps.ts
- src/components/content/order/common/utils/groupServicesByLatestVersion.ts
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/components/content/order/formDataHelpers/deployParamsHelper.ts
- src/components/content/order/formDataHelpers/serviceVendorHelper.ts
- src/components/content/order/services/Services.tsx
- src/components/content/order/services/UserServiceLatestVersionDisplayType.ts
- src/components/content/registeredServices/RegisteredServices.tsx
- src/components/content/registeredServices/tree/RegisteredServicesFullView.tsx
- src/components/content/registeredServices/tree/ServiceContent.tsx
- src/components/content/review/ServiceReviews.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/components/content/serviceConfigurationManage/ConfigurationManageScriptText.tsx
- src/components/content/serviceConfigurationManage/ServiceConfigManagement.tsx
- src/components/content/serviceConfigurationManage/ServiceConfigurationParameters.tsx
- src/components/content/serviceConfigurationManage/ServiceConfigurationScripts.tsx
- src/components/utils/constants.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2188
register:
catalog:
update:
registered service:
review service:
end user:
> rename namespace and update review table's service version.

- src/components/content/order/orderStatus/OrderSubmitResultDetails.tsx
- src/components/content/order/orderStatus/OrderSubmitStatusAlert.tsx
- src/styles/submit-result.module.css
Fixes https://github.com/eclipse-xpanse/xpanse/issues/2201
> fix error message in deployment.

- src/components/content/catalog/services/policies/AddOrUpdateServicePolicy.tsx
- src/components/content/catalog/services/policies/deletePolicy/useDeleteServicePolicy.tsx
- src/components/content/catalog/services/policies/updatePolicy/useUpdateServicePolicy.tsx
- src/components/content/common/ocl/DeploymentScript.tsx
- src/components/content/deployment/DeploymentInfomation.tsx
- src/components/content/policies/delete/useDeletePolicyRequest.tsx
- src/components/content/workflows/Workflows.tsx
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2195
Based on https://github.com/eclipse-xpanse/xpanse/pull/2244
> deployer split to multiple files

- src/components/content/deployedServices/common/DeployedServicesDetailsContent.tsx
- src/components/content/deployedServices/myServices/MyServiceDetails.tsx
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/myServices/query/useGetOrderableServiceDetailsByServiceIdQuery.ts
- src/components/content/deployedServices/reports/ReportsServiceDetails.tsx
- src/components/content/order/destroy/DestroyServiceStatusAlert.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/purge/PurgeServiceStatusAlert.tsx
- src/components/content/order/recreate/RecreateServiceStatusAlert.tsx
- src/components/content/order/serviceState/restart/RestartServiceStatusAlert.tsx
- src/components/content/order/serviceState/restart/useServiceStateRestartQuery.ts
- src/components/content/order/serviceState/start/StartServiceStatusAlert.tsx
- src/components/content/order/serviceState/start/useServiceStateStartQuery.ts
- src/components/content/order/serviceState/stop/StopServiceStatusAlert.tsx
- src/components/content/order/serviceState/stop/useServiceStateStopQuery.ts
fixes : 
https://github.com/eclipse-xpanse/xpanse/issues/2243
https://github.com/eclipse-xpanse/xpanse/issues/2242
https://github.com/eclipse-xpanse/xpanse/issues/2238
details:
purge:
start:
restart:
stop:
> update api calling and purge service state alert.

- src/components/content/catalog/services/delete/DeleteService.tsx
- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/details/serviceTemplateDetails.tsx
- src/components/content/catalog/services/details/serviceTemplateState.tsx
- src/components/content/catalog/services/republish/RepublishResult.tsx
- src/components/content/catalog/services/republish/RepublishService.tsx
- src/components/content/catalog/services/tree/CatalogFullView.tsx
- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/components/content/catalog/services/unpublish/UnpublishResult.tsx
- src/components/content/catalog/services/unpublish/UnpublishService.tsx
- src/components/content/catalog/services/update/UpdateResult.tsx
- src/components/content/catalog/services/update/UpdateService.tsx
- src/styles/catalog.module.css
- src/styles/register.module.css
Fixed eclipse-xpanse/xpanse#2110
Register:
Review:
Unpublish:
Republish：
update:
delete:
> Changes to ISV view in UI to show current status of the service template

- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/republish/RepublishService.tsx
- src/components/content/catalog/services/unpublish/UnpublishService.tsx
- src/styles/catalog.module.css
Fixed eclipse-xpanse/xpanse#2257
> tags in service detail not updated after chagnes to service state

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/migrate/MigrateServiceStatusAlert.tsx
- src/components/content/order/migrate/MigrateServiceSubmit.tsx
- src/components/content/order/migrate/MigrationOrderSubmitResult.tsx
- src/components/content/order/migrate/MigrationProcessingStatus.tsx
- src/components/content/order/retryDeployment/RetryServiceSubmit.tsx
and waiting success or failed can close the modal.
fixes [#2226](https://github.com/eclipse-xpanse/xpanse/issues/2266)
fixes [#2261](https://github.com/eclipse-xpanse/xpanse/issues/2261)
fixes [#2253](https://github.com/eclipse-xpanse/xpanse/issues/2253)
modify api always calling fixed:
scale api always calling fixed:
migrate modal can close:
click migrate opration:
migrating:
migrate successfully -show deploy success info and can close modal:
> update migrate service status api always calling

- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/history/ServiceTemplateHistory.tsx
- src/components/content/catalog/services/history/ServiceTemplateHistoryTable.tsx
- src/components/content/catalog/services/history/useRequestedServiceTemplateQuery.ts
- src/components/content/catalog/services/history/useServiceTemplateHistoryQuery.ts
- src/components/content/common/catalog/ServiceTemplateRegisterStatus.tsx
- src/styles/catalog.module.css
Fixed #eclipse-xpanse/xpanse#2111
> Add service template history view to the ISV view

- src/components/content/deployedServices/myServices/MyServices.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2267
> remove unnecessary refresh service details

- src/components/content/catalog/services/delete/DeleteResult.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/tree/CatalogFullView.tsx
- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/components/content/common/catalog/catalogProps.ts
fixes [2239](https://github.com/eclipse-xpanse/xpanse/issues/2239)
update:
delete opentofu:
delete 1.0.11:
> refresh data after service deleted.

- src/components/content/catalog/services/cancel/CancelServiceTemplateRequest.tsx
- src/components/content/catalog/services/cancel/CancelServiceTemplateRequestResult.tsx
- src/components/content/catalog/services/cancel/useCancelServiceTemplateRequest.ts
- src/components/content/catalog/services/delete/DeleteService.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/history/ServiceTemplateHistory.tsx
- src/components/content/catalog/services/history/useServiceTemplateHistoryQuery.ts
- src/components/content/catalog/services/republish/RepublishMutation.ts
- src/components/content/catalog/services/republish/RepublishResult.tsx
- src/components/content/catalog/services/republish/RepublishService.tsx
- src/components/content/catalog/services/tree/CatalogFullView.tsx
- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/components/content/catalog/services/unpublish/UnpublishMutation.ts
- src/components/content/catalog/services/unpublish/UnpublishService.tsx
Fixed eclipse-xpanse/xpanse#2231
> integrate cancel request in the UI

- src/components/content/catalog/services/update/UpdateService.tsx
Fixed eclipse-xpanse/xpanse#2259
> The parameter 'isUnpublishUntilApproved' not required when updating unavailable service template

- src/components/content/deployedServices/myServices/LocksTitle.tsx
- src/components/content/deployedServices/myServices/MigrationTitle.tsx
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/myServices/TooltipWhenDetailsDisabled.tsx
- src/components/content/deployedServices/myServices/myServiceProps.tsx
- src/components/content/order/purge/usePurgeRequestStatusQuery.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2272
fixes https://github.com/eclipse-xpanse/xpanse/issues/2278
stopping:
stopped:
starting:
running:
restarting:
running:
> update service state after stopping starting restarting finished.

- src/components/layouts/header/HeaderUserRoles.tsx
fixes: https://github.com/eclipse-xpanse/xpanse/issues/2240
> remove no unauthorized page flashes when switch role.

- src/components/content/catalog/services/history/ServiceTemplateHistoryTable.tsx
- src/components/content/deployedServices/myServices/MyServiceHistoryDetails.tsx
- src/components/content/workflows/Workflows.tsx
- src/xpanse-api/api.json
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2275
Based on https://github.com/eclipse-xpanse/xpanse/pull/2282
> update details of service order

- src/components/content/registeredServices/tree/ServiceContent.tsx
- src/styles/catalog.module.css
Fixed eclipse-xpanse/xpanse#2292
> add service template history service to CSP user

- .env.zitadel-local
related to https://github.com/eclipse-xpanse/xpanse/issues/2285
> update local zitadel connection details

- src/App.tsx
- src/components/layouts/AppLayout.tsx
- src/components/layouts/header/HeaderUserRoles.tsx
- src/components/layouts/header/LayoutHeader.tsx
- src/components/layouts/header/useCurrentRoleStore.ts
- src/components/layouts/sider/LayoutSider.tsx
- src/components/layouts/sider/menuItems.ts
- src/components/protectedRoutes/ProtectedRoute.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2298
> handle page reload and role change differently

- src/components/content/credentials/Credentials.tsx
related: https://github.com/eclipse-xpanse/xpanse/issues/2157
delete successfully:
delete failed:
> show credentials' delete alert.

- src/components/content/credentials/AddCredential.tsx
- src/components/content/credentials/CredentialProcessStatus.tsx
- src/components/content/credentials/Credentials.tsx
- src/components/content/credentials/UpdateCredential.tsx
- tests/credentials/credentials.spec.ts
- tests/utils/mocks/credentials-mock.ts
- tests/utils/pages/AddCredentialPage.ts
- tests/utils/pages/UpdateCredentialPage.ts
fixes: https://github.com/eclipse-xpanse/xpanse/issues/2327
> add failure case for credentials test.

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/serviceActions/CreateServiceActionForm.tsx
- src/components/content/order/serviceActions/ServiceActionParameter.tsx
- src/components/content/order/serviceActions/ServiceActionParameterItem.tsx
- src/components/content/order/serviceActions/elements/BooleanInput.tsx
- src/components/content/order/serviceActions/elements/NumberInput.tsx
- src/components/content/order/serviceActions/elements/TextInput.tsx
- src/components/content/order/serviceActions/useCreateServiceActionRequest.ts
- src/styles/service-action.module.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/OpenAPI.ts
- src/xpanse-api/generated/types.gen.ts
Fixed eclipse-xpanse/xpanse#2293
> add service actions to UI

- src/components/content/deployedServices/myServices/MyServices.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2330
> clicking on success alert filter the service.

- src/components/layouts/AppLayout.tsx
- src/components/protectedRoutes/ProtectedRoute.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2354
> update API token at root component

- package.json
- src/components/content/common/queries/useServiceDetailsByServiceIdQuery.ts
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/orderStatus/OrderEndPointDetails.tsx
- src/components/content/order/orderStatus/OrderProcessingStatus.tsx
- src/components/content/order/orderStatus/OrderSubmitStatusAlert.tsx
- src/components/content/order/orderStatus/ProcessingStatus.tsx
- src/components/content/order/retryDeployment/RetryServiceSubmit.tsx
- src/components/content/order/retryDeployment/useRedeployFailedDeploymentQuery.ts
- src/components/content/order/types/OperationType.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2347
> refactor status polling to use order status only

- src/components/content/common/doc/ApiDoc.tsx
- src/components/content/common/ocl/ContactDetailsText.tsx
- src/components/content/order/common/IsvNameDisplay.tsx
- src/components/content/order/create/NewOrderHeaderElements.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
- src/styles/ocl-display.module.css
- src/styles/service-order.module.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/2335
> make elements in new order pages show in fixed postion.

- src/components/content/order/create/CreateService.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/create/SelectServiceForm.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2333
https://github.com/user-attachments/assets/9c8aef3d-3b29-4b8b-bb39-cbddd3c149f1
> make service category selection work.

- src/components/content/deployedServices/myServices/MyServices.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2348
> update auto filter of service id from successful deployment.

- src/App.tsx
- src/components/oidc/ConditionalOidcProtectedLayout.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2378
> secure entire layout to avoid any unauthenticated API calls

- src/components/content/order/common/ServiceChangeResultDetails.tsx
- src/components/content/order/common/ServiceChangeSubmitResult.tsx
- src/components/content/order/common/formItemElements/TextInput.tsx
- src/components/content/order/orderStatus/OrderProcessingStatus.tsx
- src/components/content/order/serviceActions/CreateServiceActionForm.tsx
- src/components/content/order/serviceActions/ServiceActionParameter.tsx
- src/components/content/order/serviceActions/ServiceActionStatusAlert.tsx
- src/components/content/order/serviceConfiguration/ServiceConfigStatusAlert.tsx
- src/components/content/order/types/OperationType.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2430
updated:
submitting:
submit failed:
https://github.com/user-attachments/assets/9391f8f0-17dc-4e08-80cb-11d882bff362
> extend actions in the myServices table.

- src/xpanse-api/api.json
- src/xpanse-api/generated/types.gen.ts
> update client api

- src/components/content/order/common/ScaleOrModifyOrderSubmitResult.tsx
- src/components/content/order/common/ScaleOrModifySubmitStatusAlert.tsx
- src/components/content/order/common/ServiceStateSubmitResult.tsx
- src/components/content/order/destroy/DestroyOrderSubmitResult.tsx
- src/components/content/order/destroy/DestroyServiceStatusAlert.tsx
- src/components/content/order/orderStatus/OrderProcessingStatus.tsx
- src/components/content/order/orderStatus/OrderSubmitResult.tsx
- src/components/content/order/orderStatus/OrderSubmitResultDetails.tsx
- src/components/content/order/orderStatus/OrderSubmitStatusAlert.tsx
- src/components/content/order/purge/PurgeOrderSubmitResult.tsx
- src/components/content/order/purge/PurgeServiceStatusAlert.tsx
- src/components/content/order/recreate/RecreateOrderSubmitResult.tsx
- src/components/content/order/recreate/RecreateServiceStatusAlert.tsx
- src/components/content/order/servicePorting/PortServiceStatusAlert.tsx
- src/components/content/order/serviceState/restart/RestartServiceStatusAlert.tsx
- src/components/content/order/serviceState/start/StartServiceStatusAlert.tsx
- src/components/content/order/serviceState/stop/StopServiceStatusAlert.tsx
- src/components/content/order/types/OperationType.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2442
Deploying:
Deployment Successful:
Porting:
Service ported successfully:
Scaling:
Modification Successful:
Modifing:
Modification Successful:
Recreating:
Recreation Successful:
Starting:
Service started successfully:
Stopping:
Service stopped successfully:
Restarting:
Service restarted successfully:
Destroying:
Destroyed Successfully:
Service purged successfully:
> display order id.

- src/components/content/systemStatus/HealthCheckStatus.tsx
- src/components/content/systemStatus/useStackStatusCheckQuery.ts
- src/xpanse-api/api.json
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
- tests/admin/healthcheck/health-check.spec.ts
- tests/header/layout-header.spec.ts
- tests/utils/mocks/endpoints.ts
- tests/utils/mocks/health-check-mock.ts
- tests/utils/mocks/stack-check-mocks.ts
[Backend PR](https://github.com/eclipse-xpanse/xpanse/pull/2425)
1. Generate new clients -> xpanse/stack/health
2. Point HealthCheckStatus rsp to new response
>  AdminService API Changes

- src/components/content/deployedServices/myServices/MyServiceHistory.tsx
- src/components/content/deployedServices/myServices/MyServiceHistoryDetails.tsx
- src/components/content/order/common/FlavorFeatures.tsx
- src/components/content/order/common/FlavorPrice.tsx
- src/components/content/order/modify/Modify.tsx
- src/components/content/order/scale/Scale.tsx
- src/styles/service-operation.module.css
fixes https://github.com/eclipse-xpanse/xpanse/issues/2419
updated:
> update request body for order history.

- src/components/content/credentials/Credentials.tsx
- src/components/content/deployedServices/myServices/MyServiceHistory.tsx
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/myServices/SelectMyServicesColumns.tsx
- src/components/content/deployedServices/myServices/myServiceProps.tsx
- src/components/content/order/common/ShowId.tsx
- src/components/content/userPolicies/UserPolicies.tsx
- src/components/content/workflows/Workflows.tsx
- src/components/layouts/header/HeaderUserRoles.tsx
- src/components/layouts/header/SearchServices.tsx
- src/styles/app.module.css
- src/styles/header.module.css
- src/styles/my-services.module.css
- src/styles/service-operation.module.css
- src/styles/show-id.module.css
- src/styles/table.module.css
- tests/utils/pages/CredentialsPage.ts
fixes: https://github.com/eclipse-xpanse/xpanse/issues/2377
updated:
https://github.com/user-attachments/assets/d842dd3d-1b57-4b3e-bd9a-35a16b353f13
https://github.com/user-attachments/assets/439b8821-1487-42a2-b57c-5a74b70daaff
> make myServices table can be selectable.

- src/components/content/catalog/services/policies/AddOrUpdateServicePolicy.tsx
- src/components/content/catalog/services/policies/ServicePolicies.tsx
- src/components/content/catalog/services/policies/deletePolicy/ServicePolicyDeleteStatus.tsx
- src/components/content/userPolicies/AddOrUpdateUserPolicy.tsx
- src/components/content/userPolicies/UserPolicies.tsx
- src/components/content/userPolicies/delete/UserPolicyDeleteResultStatus.tsx
- tests/policies/policies.spec.ts
- tests/utils/common/policies/test_policies.rego
- tests/utils/mocks/endpoints.ts
- tests/utils/mocks/policies-mock.ts
- tests/utils/pages/AddPolicyPage.ts
- tests/utils/pages/PoliciesPage.ts
- tests/utils/pages/UpdatePolicyPage.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2255.
> add policies test.

- tests/order/service-order.spec.ts
- tests/utils/mocks/endpoints.ts
- tests/utils/mocks/service-order-mock.ts
- tests/utils/pages/MyServicesPage.ts
- tests/utils/pages/OrderSubmitPage.ts
- tests/utils/pages/SelectServicePage.ts
- tests/utils/pages/ServiceOrderPage.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2361
> add order test.

- tests/isv/register/register.spec.ts
- tests/utils/mocks/endpoints.ts
- tests/utils/mocks/service-register-mock.ts
- tests/utils/pages/DownloadYmlFile.ts
- tests/utils/pages/ServiceRegisterPage.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2496
> add register test.

- src/components/content/catalog/services/cancel/CancelServiceTemplateRequest.tsx
- src/components/content/catalog/services/cancel/CancelServiceTemplateRequestResult.tsx
- src/components/content/catalog/services/delete/DeleteResult.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/republish/RepublishResult.tsx
- src/components/content/catalog/services/unpublish/UnpublishResult.tsx
- src/components/content/common/error/RetryPrompt.tsx
- src/components/utils/constants.tsx
- tests/isv/catalog/service-catalog.spec.ts
- tests/utils/mocks/endpoints.ts
- tests/utils/mocks/service-catalog-mock.ts
- tests/utils/pages/DownloadYmlFile.ts
- tests/utils/pages/ServiceCatalogPage.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2497
> add catalog test.

- src/components/content/catalog/services/details/ServiceDetail.tsx
- src/components/content/common/ocl/DisplayOclData.tsx
- src/components/content/review/ServiceReviewsDetails.tsx
- src/components/content/serviceObjectsManage/ServiceObjectItems.tsx
- src/components/content/serviceObjectsManage/ServiceObjectManageItems.tsx
- src/components/content/serviceObjectsManage/ServiceObjectParameters.tsx
- src/components/content/serviceObjectsManage/ServiceObjectScripts.tsx
- src/components/content/serviceObjectsManage/ServiceObjectsManagement.tsx
- src/styles/service-objects.module.css
- src/xpanse-api/api.json
- src/xpanse-api/generated/core/OpenAPI.ts
- src/xpanse-api/generated/sdk.gen.ts
- src/xpanse-api/generated/types.gen.ts
fises https://github.com/eclipse-xpanse/xpanse/issues/2515
register:
catalog:
review:
Registered service:
> show service objects for service template.

- src/components/content/catalog/services/cancel/CancelServiceTemplateRequest.tsx
- src/components/content/catalog/services/cancel/CancelServiceTemplateRequestResult.tsx
- src/components/content/catalog/services/delete/DeleteResult.tsx
- src/components/content/catalog/services/delete/DeleteService.tsx
- src/components/content/catalog/services/details/ServiceProvider.tsx
- src/components/content/catalog/services/details/serviceTemplateAction.tsx
- src/components/content/catalog/services/republish/RepublishResult.tsx
- src/components/content/catalog/services/republish/RepublishService.tsx
- src/components/content/catalog/services/tree/CatalogFullView.tsx
- src/components/content/catalog/services/tree/CategoryCatalog.tsx
- src/components/content/catalog/services/unpublish/UnpublishMutation.ts
- src/components/content/catalog/services/unpublish/UnpublishResult.tsx
- src/components/content/catalog/services/unpublish/UnpublishService.tsx
- tests/utils/pages/ServiceCatalogPage.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2553
> remove multiple alerts in service template actions

- src/xpanse-api/CustomOpenApiConfig.ts
- src/xpanse-api/timezone.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/2448
> display timestamp field using local timezone

- src/components/content/common/queries/useLatestServiceOrderStatusQuery.ts
- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/deployedServices/myServices/myServiceProps.tsx
- src/components/content/order/create/OrderSubmit.tsx
- src/components/content/order/modify/Modify.tsx
- src/components/content/order/scale/Scale.tsx
- src/components/content/order/scale/ScaleModal.tsx
- src/components/content/order/serviceActions/ServiceActionParameter.tsx
- src/components/content/order/serviceConfiguration/ServiceConfigurationDetails.tsx
- src/components/content/order/servicePorting/PortServiceSubmit.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2580
> fix polling and unify service operations for all types. Ensure all operations are allowed for all other services for which a change was not requested

- src/components/content/deployedServices/myServices/MyServices.tsx
- src/components/content/order/common/FlavorSelection.tsx
- src/components/content/order/orderStatus/OrderEndPointDetails.tsx
- src/components/content/order/orderStatus/OrderProcessingStatus.tsx
- src/components/content/order/orderStatus/OrderSubmitResultDetails.tsx
- src/components/content/order/servicePorting/PortServiceOrderSubmitResult.tsx
- src/components/content/order/servicePorting/PortServiceStatusAlert.tsx
- src/components/content/order/servicePorting/PortServiceSubmit.tsx
- src/components/content/order/servicePorting/ServicePorting.tsx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2605
> fix service porting detail links when modal is open.
